### ISSUE TITLE
data_feed_test.ex randomly fails

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/reaper#131]
The data_feed_test.ex fails randomly when testing the update functionality.  This random failure is drag on the development team because the build will randomly fail for invalid reasons.

**Comment by ManApart** [comment]
Looking at past failed master builds I'm seeing a couple reoccurring errors, but not data_feed_test.ex. What build number is a good example of data_feed_test.ex failing?


Seen errors:
```
test update scenarios reaper config updates replace old state (Reaper.DataFeedSchedulerTest)
     test/unit/reaper/data_feed_scheduler_test.exs:38
     ** (EXIT from #PID<0.7824.0>) an exception was raised:
         ** (File.Error) could not read file "12345-6789": no such file or directory
             (elixir) lib/file.ex:353: File.read!/1
             (reaper) lib/reaper/decoder/gtfs.ex:11: Reaper.Decoder.Gtfs.decode/2
             (reaper) lib/reaper/decoder.ex:33: Reaper.Decoder.decode/2
             (reaper) lib/reaper/data_feed.ex:34: Reaper.DataFeed.process/2
             (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
             (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

https://travis-ci.org/smartcitiesdata/reaper/builds/572020702
```
** (RuntimeError) Bring this thing down!
         test/integration/reaper/reaper_full_test.exs:105: anonymous fn/4 in Reaper.FullTest.__ex_unit_setup_2/1
         (reaper) lib/reaper/data_feed/load_stage.ex:64: Reaper.DataFeed.LoadStage.process_batch/1
         (reaper) lib/reaper/data_feed/load_stage.ex:33: Reaper.DataFeed.LoadStage.terminate/2
         (stdlib) gen_server.erl:673: :gen_server.try_terminate/3
         (stdlib) gen_server.erl:858: :gen_server.terminate/10
         (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

https://travis-ci.org/smartcitiesdata/reaper/builds/573522432
```
test update scenarios reaper config updates replace old state (Reaper.DataFeedSchedulerTest)
     test/unit/reaper/data_feed_scheduler_test.exs:38
     ** (EXIT from #PID<0.7851.0>) an exception was raised:
         ** (File.Error) could not read file "12345-6789": no such file or directory
```
